### PR TITLE
Fix infinite loop bug in deliveryAck

### PR DESCRIPTION
**Pull request by Henderake**
Fix an infinite loop bug in https://github.com/gocelery/gocelery/issues/117
If RabbitMQ is down then deliveryAck will retry indefinitely and consume a lot of CPU resources.

### CODE REVIEW

**Comment by Henderake** [comment]
CI tests fail because rabbitmq can't be started. Is it related to [this problem on Travis](https://travis-ci.community/t/is-rabbitmq-service-down/4362)?

**Comment by sickyoon** [comment]
@Henderake thanks for bringing this matter to my attention. I committed the necessary changes. Could you rebase off master and try again?

**Comment by Henderake** [comment]
What's the difference between the tests in `go test` and `goveralls`? In CI, the test TestWorkerStartStop succeeded in `go test` but somehow failed in `goveralls`

**Comment by Henderake** [comment]
I just fixed the CI test. It turns out that it requires more than 10s for the Redis broker/backend test case to stop the worker.

**Comment by Henderake** [comment]
@sickyoon Are there any changes still need to be made?

**Pull request merged**
