### PR TITLE
Issue 75

### PR DESCRIPTION
**Pull request by phamdt**
work in progress

This PR addresses #75.

### CODE REVIEW

**Comment by phamdt** [comment]
The implementation and tests are mostly copy/pasting from your int example. While the single test included passes, I want to add a bit more. To do so, I'd like to do some test refactoring to use table driven tests. Additionally, I was going to add a docker-compose file to make it easy for people to get a local demo up easily (and also to have something to test against). That is also a WIP. I thought I'd check-in before going to deep.

**Comment by phamdt** [comment]
oh, just realized my master is behind...more to come!

**Comment by sickyoon** [comment]
I think docker-compose is unnecessary.
Please create an issue before you start working on PR.
Also isolate problems you are trying to solve.
Float32 might not work due to json limitation but you can try.

**Comment by phamdt** [comment]
ah i see that you already started an implementation. i'll close this and revisit your skipped test. now that my master is up to date i'll make a new PR from there.

**Pull request closed without merging**
